---
- name: Create multiple users
  hosts: myservers
  become: yes
  tasks:

    - name: Create users with loop
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - saleh
        - miri
        - sahar
        - atena
        - babak
        - mani
