---
- name: Simple example of Ansible handlers
  hosts: myservers
  become: yes
  tasks:

    - name: Ensure httpd package is present
      yum:
        name: httpd
        state: latest
      notify: restart_httpd

  handlers:

    - name: restart_httpd
      service:
        name: httpd
        state: restarted
