---
- name: Add DNS server to resolv.conf
  hosts: myservers
  vars:
    dns_server: 4.2.2.4
  tasks:
    - name: append nameserver
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver {{ dns_server }}"


