---
- hosts: all
  become: yes
  tasks:

    - name: Show OS family
      debug:
        msg: "OS Family is {{ ansible_facts.os_family }}"

    - name: Show distribution name
      debug:
        msg: "Distribution is {{ ansible_facts.distribution }}"

    - name: Show distribution version
      debug:
        msg: "Version is {{ ansible_facts.distribution_version }}"

    - name: Show default IP address
      debug:
        msg: "IP Address is {{ ansible_facts.default_ipv4.address }}"
